---
name: Test
on:
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: read
jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 18.0.0
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install@8
      - name: Ensure dependencies are compatible with the version of node
